using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DNextBtn : MonoBehaviour
{
    public DiaryReading Diary;
    private AudioSource audio;
    private void Start()
    {
        audio = GetComponent<AudioSource>();
        audio.volume = musicData.musicValue;
        if (musicData.isOpenBE)
        {
            audio.Play();
        }
        else
        {
            audio.Stop();
        }
    }
    private void OnMouseDown()
    {
        Diary.currentIndex++;
        if (Diary.currentIndex >= Diary.diarySprites.Count)
        {
            Diary.currentIndex = Diary.diarySprites.Count - 1; // 횅괏乞多꼇낚법죗깊낀똑
        }
        audio.Play();
        Diary.nowPage.sprite = Diary.diarySprites[Diary.currentIndex]; // 뫘劤뎠품鞫刻돨휑션暠튬
    }
}
